version: "3.1"
services:
    www:
        image: php:7.3-apache
        ports: 
            - "8007:80"
        volumes:
            - ./src/:/var/www/html/
        networks:
            - default
volumes:
    persistent: